name: Deploy ASP.NET Core to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish to folder
        run: |
          dotnet publish src/AguaDulce.Web/AguaDulce.Web.csproj \
            -c Release -o publish

      - name: Deploy to Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'aguadulce-webapp'               # el nombre de tu App Service
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: publish