name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read       # lectura del repo
  pages: write         # permite publicar en gh-pages
  id-token: write      # si usas OIDC (opcional)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # evita sobreescribir el token

      # ... build de tu sitio (npm, dotnet publish, etc.) ...

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # o la carpeta resultante de tu build