# .github/workflows/gh-pages.yml

name: Deploy Front estático to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona tu repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Publica la carpeta docs/ en la rama main (GitHub Pages)
      - name: Deploy docs folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: docs