# .github/workflows/gh-pages.yml

name: Deploy Front estático to GitHub Pages

permissions:
  contents: write   # permitir push en ramas/repos
  pages: write      # permitir deploy a GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Si necesitas generear tu frontend, descomenta:
      # - name: Build frontend
      #   run: |
      #     npm ci
      #     npm run build
      #     cp -R build/* docs/

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs